services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
    - "5252:5252"

  fron-tend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - back-end
      