services:
  back-end:
    build:
      context: back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task6
    networks:
      - my_network

  front-end:
    build:
      context: front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task6
    depends_on:
      - back-end
    networks:
      - my_network

  proxy:
    build: 
      context: proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task6
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end
    networks:
      - my_network

networks:
  my_network:
    driver: bridge